### ISSUE TITLE
BUG: Cannot set `placement` correctly using `forRoot()`

### ISSUE THREAD

**Issue by slack4u** [tonysamperi/ngx-popperjs#14]
**Describe the bug**
Cannot set `placement` correctly using `forRoot()`.

**To Reproduce**
1. Set `placement` to `forRoot()` as follows: `NgxPopperjsModule.forRoot({placement: NgxPopperjsPlacements.BOTTOMEND})`
2. Click on the following element: `<div popper="Message" [popperTrigger]="'click'">Text</div>`
3. It should be displayed at the `bottom-end` , but it is displayed as `auto` .

**Expected behavior**
Make sure that `placement` is properly specified in `forRoot()`.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Microsoft Edge
 - Version: 92.0.902.78

**Comment by alberthaff** [comment]
I'm having the same problem in Chrome.

@angular/core: 12.2.6
@popperjs/core: 2.10.1
ngx-popperjs: 12.1.2

**Comment by tonysamperi** [comment]
@alberthaff yes, it's a js problem so it's on all browsers...and probably on all versions of the lib since probably it was never fixed in the original.
I'm having a really hard time right now, if you guys want to try a pull request it would definitely speed up the process...
Otherwise I need a couple weeks till I will be able to fix it myself.

**Comment by alberthaff** [comment]
I figured it was a general issue. 
Okay, no rush. I'll see if i have time to look into it, but i'm also kinda busy. :-)

**Comment by alberthaff** [comment]
@tonysamperi Awesome, thanks!

**Comment by slack4u** [comment]
@tonysamperi Thank you so much!
